[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "kea"
version = "1.0"
authors = [
  { name="Mark Bishop", email="mark.bishop@vuw.ac.nz" },
]
description = "A short description of your package"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "numpy>=1",
    "scipy>=1",
    "sympy>=1",
    "matplotlib>=3",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
    "pytest-cov>=5.0.0",
]
gpu = [
  "cupy",
  "mpi4py",
]

[project.urls]
"Homepage" = "https://github.com/mab68/kea"
"Bug Tracker" = "https://github.com/mab68/kea/issues"

[tool.setuptools.packages.find]
where = ["src"]
