"""
Provides functions to generate random masks.
"""

from kea.simulator import synthesize

import numpy as np

def _create_circle(
        index_grid: np.ndarray,
        center_position: tuple[int,...],
        radius: int) -> np.ndarray:
    """_create_circle(index_grid, center_position, radius)\n

    Create circle with `radius` centered on the grid at `center_position`
    
    Args:
        index_grid (np.ndarray): Array representing the indices of the grid
        center_position (tuple): Location of the center of the circle
        radius (int): Radius of the circle
    
    Returns:
        np.ndarray: Boolean array; True where the circle exists
    """
    ndim = np.shape(index_grid)[0]
    centered_grid = np.linalg.norm([index_grid[i,...] - center_position[i] for i in range(ndim)], axis=0)
    return centered_grid <= radius
    
def create_mask(grid_dims, mask_type='circles', mask_kwargs={}, missing_fraction=0.5):
    """create_mask(grid_dims, mask_type, p)\n

    Create a mock (random) mask.

    Args:
        grid_dims (tuple): Shape of the mask; number of pixels in each dimension
        mask_type (str): 
            - "circles": mask generated by placing random blobs (circles)
            - "outside": Defines a mask from a simple circular cutoff
            - "random_field": Mask generated using stochastic fields
        mask_kwargs (dict):
            - "circles": {"maximum_radius": float,}
            - "outside": {}
            - "random_field": {"spectrum_kwargs": {}, "spectrum_function": str, "cutoff_step": float}
        missing_fraction (float): Fraction of data to remove

    Returns:
        np.ndarray: Mask to indicate bad data
    """
    assert len(set(grid_dims)) <= 1, 'Must have the same number of points in each dimension'
    valid_fraction = 1. - missing_fraction
    mask = np.ones(grid_dims)

    if mask_type == 'circles':
        ndim = len(grid_dims)
        total_points = np.prod(grid_dims)
        index_grid = np.indices(grid_dims)
        while np.sum(mask)/total_points > valid_fraction:
            # Generate a random position
            random_center = tuple([np.random.randint(0, grid_dims[i]) for i in range(ndim)])
            # Generate a random radius, maximum radius: 1/16 of the domain size
            maximum_radius = mask_kwargs.get('maximum_radius', grid_dims[0]//16)
            if maximum_radius <= 1:
                ## Small grid, so just make circles 1-2 pixels in radius
                maximum_radius = 2
            random_radius = np.random.randint(1, maximum_radius)
            circle_mask = _create_circle(index_grid, random_center, random_radius)
            mask[circle_mask] = 0.

    elif mask_type == 'outside':
        # Formula for the radius of circle to remove an area corresponding to `missing_fraction`
        radius_cut = np.sqrt(valid_fraction * grid_dims[0]**2 / np.pi)
        index_grid = np.indices(grid_dims)
        # Center grid in the center of the image
        centered_grid = np.linalg.norm([index_grid[i,...] - n//2 for i, n in enumerate(grid_dims)], axis=0)
        outside_mask = centered_grid > radius_cut
        mask[outside_mask] = 0.

    elif mask_type == 'random_field':
        # Iterate through possible values, slowly increasing the cutoff until `missing_fraction`
        current_fraction = 0.
        cuttoff_value = 0.
        # Step-size for the iteration cutoff
        cutoff_step = mask_kwargs.get('cutoff_step', 0.2)
        while current_fraction < missing_fraction:
            # Make field
            field_mask = synthesize.make_field(
                grid_dims,
                mask_kwargs['spectrum_kwargs'],
                mask_kwargs['spectrum_function'],
                normalize_output=True)

            # Generate binary mask from `cutoff_value`
            mask[np.abs(field_mask) < cuttoff_value] = 0.
            mask[np.abs(field_mask) >= cuttoff_value] = 1.

            # Update current missing fraction and next cutoff value
            current_fraction = 1. - (np.sum(mask) / np.prod(grid_dims))
            cuttoff_value = cuttoff_value + cutoff_step
    else:
        raise NotImplementedError('Unknown mask type (%s)' % mask_type)

    return mask
