name: kea
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip

  # computing
  - numpy
  - scipy
  - sympy
  - matplotlib
  - astropy
  - healpy

  # documentation
  - sphinx
  - furo
  - myst-parser
  - nbsphinx
  - nbsphinx-link
  - sphinx-autodoc-typehints
  - sphinxcontrib-bibtex
  - pandoc

  - pip:
    - pyspedas